name: stream_value
description: A simple wrap over StreamController and StreamBuilder that reduces the boilerplate to use Streams as State Management.
version: 0.0.5
repository: https://github.com/belluga/stream_value

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0